name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        
    - name: Run tests
      run: sbt test
      
    - name: Indigo build
      run: sbt buildGame
      
    - name: Publish game
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: meblabs.com
        username: ${{ secrets.ftp_admin }}
        password: ${{ secrets.ftp_psw }}
        local-dir: ./target/indigoBuild/
        dangerous-clean-slate: true
